
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 20/5/2022 - 04:29 p. m.
// This is a partial class file. The other one is CalificacionesObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace monaguaRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CalificacionesObject : BaseObject, IMappeableCalificacionesObject, IUniqueIdentifiable, IEquatable<CalificacionesObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public CalificacionesObject(): base()
        {

			_IdCalificacion =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public CalificacionesObject(
			System.Int32 IdCalificacion): base()
        {

			_IdCalificacion = IdCalificacion;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public CalificacionesObject(
			System.Int32 IdCalificacion,
			System.DateTime Fecha,
			System.Int32 IdCompraDetalle,
			System.Int32 Calificacion,
			System.String Comentario,
			System.String Respuesta): base()
        {

			_IdCalificacion = IdCalificacion;
			_Fecha = Fecha;
			_IdCompraDetalle = IdCompraDetalle;
			_Calificacion = Calificacion;
			_Comentario = Comentario;
			_Respuesta = Respuesta;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdCalificacion;
/// <summary>
/// 
/// </summary>
protected System.DateTime _Fecha;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdCompraDetalle;
/// <summary>
/// 
/// </summary>
protected System.Int32 _Calificacion;
/// <summary>
/// 
/// </summary>
protected System.String _Comentario;
/// <summary>
/// 
/// </summary>
protected System.String _Respuesta;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdCalificacion
        {
            get
            {
                return _IdCalificacion;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            
            set
            {
                base.PropertyModified();
                _Fecha = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdCompraDetalle
        {
            get
            {
                return _IdCompraDetalle;
            }
            
            set
            {
                base.PropertyModified();
                _IdCompraDetalle = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Calificacion
        {
            get
            {
                return _Calificacion;
            }
            
            set
            {
                base.PropertyModified();
                _Calificacion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            
            set
            {
                base.PropertyModified();
                _Comentario = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Respuesta
        {
            get
            {
                return _Respuesta;
            }
            
            set
            {
                base.PropertyModified();
                _Respuesta = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            CalificacionesObject newObject;
            CalificacionesObject newOriginalValue;

            newObject = (CalificacionesObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (CalificacionesObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new CalificacionesObject OriginalValue()
        {
            return (CalificacionesObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCalificacionesObject.HydrateFields(
			System.Int32 IdCalificacion,
			System.DateTime Fecha,
			System.Int32 IdCompraDetalle,
			System.Int32 Calificacion,
			System.String Comentario,
			System.String Respuesta)
        {
        _IdCalificacion = IdCalificacion;
_Fecha = Fecha;
_IdCompraDetalle = IdCompraDetalle;
_Calificacion = Calificacion;
_Comentario = Comentario;
_Respuesta = Respuesta;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCalificacionesObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[6];
            _myArray[0] = _IdCalificacion;
_myArray[1] = _Fecha;
_myArray[2] = _IdCompraDetalle;
_myArray[3] = _Calificacion;
_myArray[4] = _Comentario;
if (!System.String.IsNullOrEmpty(_Respuesta)) _myArray[5] = _Respuesta;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCalificacionesObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[6];
            _myArray[0] = _IdCalificacion;
_myArray[1] = _Fecha;
_myArray[2] = _IdCompraDetalle;
_myArray[3] = _Calificacion;
_myArray[4] = _Comentario;
if (!System.String.IsNullOrEmpty(_Respuesta)) _myArray[5] = _Respuesta;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCalificacionesObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdCalificacion;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCalificacionesObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _IdCalificacion = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            CalificacionesObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdCalificacion};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(CalificacionesObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableCalificacionesObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdCalificacion, 
			System.DateTime Fecha, 
			System.Int32 IdCompraDetalle, 
			System.Int32 Calificacion, 
			System.String Comentario, 
			System.String Respuesta);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class CalificacionesObjectList : ObjectList<CalificacionesObject>
    {
    }
}

namespace monaguaRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CalificacionesObjectListView
        : ObjectListView<Objects.CalificacionesObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public CalificacionesObjectListView(Objects.CalificacionesObjectList list): base(list)
        {
        }
    }
}


