
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 22/11/2022 - 11:25
// This is a partial class file. The other one is EstadosCompraActividadObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace monaguaRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class EstadosCompraActividadObject : BaseObject, IMappeableEstadosCompraActividadObject, IUniqueIdentifiable, IEquatable<EstadosCompraActividadObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public EstadosCompraActividadObject(): base()
        {


        }

        /// <summary>
        /// 
        /// </summary>
        public EstadosCompraActividadObject(
			System.Int32 IdEstadoActividad): base()
        {

			_IdEstadoActividad = IdEstadoActividad;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public EstadosCompraActividadObject(
			System.Int32 IdEstadoActividad,
			System.String Nombre): base()
        {

			_IdEstadoActividad = IdEstadoActividad;
			_Nombre = Nombre;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdEstadoActividad;
/// <summary>
/// 
/// </summary>
protected System.String _Nombre;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdEstadoActividad
        {
            get
            {
                return _IdEstadoActividad;
            }
            
            set
            {
                base.PropertyModified();
                _IdEstadoActividad = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            
            set
            {
                base.PropertyModified();
                _Nombre = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            EstadosCompraActividadObject newObject;
            EstadosCompraActividadObject newOriginalValue;

            newObject = (EstadosCompraActividadObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (EstadosCompraActividadObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new EstadosCompraActividadObject OriginalValue()
        {
            return (EstadosCompraActividadObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableEstadosCompraActividadObject.HydrateFields(
			System.Int32 IdEstadoActividad,
			System.String Nombre)
        {
        _IdEstadoActividad = IdEstadoActividad;
_Nombre = Nombre;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableEstadosCompraActividadObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[2];
            _myArray[0] = _IdEstadoActividad;
_myArray[1] = _Nombre;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableEstadosCompraActividadObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[3];
            _myArray[0] = _IdEstadoActividad;
_myArray[1] = _Nombre;
_myArray[2] = this.OriginalValue()._IdEstadoActividad;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableEstadosCompraActividadObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdEstadoActividad;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableEstadosCompraActividadObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            
        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            EstadosCompraActividadObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdEstadoActividad};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(EstadosCompraActividadObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableEstadosCompraActividadObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdEstadoActividad, 
			System.String Nombre);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class EstadosCompraActividadObjectList : ObjectList<EstadosCompraActividadObject>
    {
    }
}

namespace monaguaRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class EstadosCompraActividadObjectListView
        : ObjectListView<Objects.EstadosCompraActividadObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public EstadosCompraActividadObjectListView(Objects.EstadosCompraActividadObjectList list): base(list)
        {
        }
    }
}


