
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 21/09/2022 - 17:27
// This is a partial class file. The other one is EstadosCompraActividadEntity.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using System;
using Cooperator.Framework.Core.Exceptions;

namespace monaguaRules.Entities
{
    /// <summary>
    /// This class represents the EstadosCompraActividad entity.
    /// </summary>
    [Serializable]
    public partial class EstadosCompraActividad
        // : IValidable
    {
        // /// <summary>
        // /// When IValidable is implemented, this method is invoked by Gateway before Insert or Update to validate Object.
        // /// </summary>
        // public void Validate()
        // {
        //     //Example:
        //     if (string.IsNullOrEmpty(this.Name)) throw new RuleValidationException("Name can't be null");
        // }
    }

    /// <summary>
    /// This class represents a collection of EstadosCompraActividad entity.
    /// </summary>
    public partial class EstadosCompraActividadList
    {
         // /// <summary>
         // /// Returns a typed Dataset based on its content.
         // /// </summary>
         //public override System.Data.DataSet ToDataSet()
         //{
         //    YOUR_TYPED_DATASET MyDataSet = new YOUR_TYPED_DATASET();
         //    ObjectListHelper<EstadosCompraActividad, EstadosCompraActividadList> Exporter = new ObjectListHelper<EstadosCompraActividad, EstadosCompraActividadList>();
         //    Exporter.FillDataSet(MyDataSet, this);
         //    return MyDataSet;
         //}
    }
}

namespace monaguaRules.Views
{
    /// <summary>
    /// This class represents a view of an collection of EstadosCompraActividad entities.
    /// </summary>
    public partial class EstadosCompraActividadListView
    {
    }
}


