
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 15/09/2022 - 16:08
// This is a partial class file. The other one is PreguntasFrecuentesEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using monaguaRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace monaguaRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class PreguntasFrecuentes : Objects.PreguntasFrecuentesObject, IMappeablePreguntasFrecuentes, IEquatable<PreguntasFrecuentes>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public PreguntasFrecuentes()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public PreguntasFrecuentes(
			System.Int32 IdPregunta)
            : base()
        {

			_IdPregunta = IdPregunta;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public PreguntasFrecuentes(
			System.Int32 IdPregunta,
			System.String Pregunta,
			System.String Respuesta,
			System.Int32 Orden,
			System.Boolean Activa)
            : base()
        {

			_IdPregunta = IdPregunta;
			_Pregunta = Pregunta;
			_Respuesta = Respuesta;
			_Orden = Orden;
			_Activa = Activa;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new PreguntasFrecuentes OriginalValue()
        {
            return (PreguntasFrecuentes)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            PreguntasFrecuentes newObject;            
            

            newObject = (PreguntasFrecuentes)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            PreguntasFrecuentes newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (PreguntasFrecuentes)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeablePreguntasFrecuentes.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeablePreguntasFrecuentes.SetFKValuesForChilds(PreguntasFrecuentes entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(PreguntasFrecuentes other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeablePreguntasFrecuentes
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(PreguntasFrecuentes entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class PreguntasFrecuentesList : ObjectList<PreguntasFrecuentes>
    {
    }
}
namespace monaguaRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class PreguntasFrecuentesListView
        : ObjectListView<Entities.PreguntasFrecuentes>
    {
        /// <summary>
        /// 
        /// </summary>
        public PreguntasFrecuentesListView(Entities.PreguntasFrecuentesList list): base(list)
        {
        }
    }
}


