import { ActividadesHorarios } from "./ActividadesHorarios.model";
import { Calificaciones } from "./Calificaciones.model";
import { Categorias } from "./Categorias.model";
import { Localidades } from "./Localidades.model";
import { Prestadores } from "./Prestadores.model";
import { Provincias } from "./Provincias.model";

export class Actividades{
    IdActividad:number;
    Nombre:string;
    DescripcionCorta:string;
    Descripcion:string;
    Fotos:string;
    Video:string;
    Mapa:string;
    Ubicacion:string;
    Precio:number;
    PrecioOferta:number;
    Mascotas:boolean;
    PersonasCapacidadRed:boolean;
    DietasEspeciales:boolean;
    Idiomas:string;
    Dificultad:string;
    QueIncluye:string;
    QueNoIncluye:string;
    Duracion:number;
    IdCategoria:number;
    IdPrestador:number;
    Activa:boolean;
    CategoriasEntity:Categorias;
    PrestadoresEntity:Prestadores;
    Horarios:ActividadesHorarios[]=[];
    CancelacionGratuita:boolean;
    Calificacion:number;
    cantCalificaciones:number;
    calificacionesList:Calificaciones[]=[];
    DiasCancelacion:number;
    LocalidadesEntity?:Localidades;
    ProvinciasEntity?:Provincias;
    IdProvincia:number;
    IdLocalidad:number;
}