
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 31/08/2022 - 14:49
// This is a partial class file. The other one is SlidesMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using monaguaRules.Entities;
using monaguaRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace monaguaRules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class SlidesMapper : BaseGateway<Slides, SlidesList>, IGenericGateway
    {


        #region "Singleton"

        static SlidesMapper _instance;

        private SlidesMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static SlidesMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new SlidesMapper();
                else {
                    SlidesMapper inst = HttpContext.Current.Items["monaguaRules.SlidesMapperSingleton"] as SlidesMapper;
                    if (inst == null) {
                        inst = new SlidesMapper();
                        HttpContext.Current.Items.Add("monaguaRules.SlidesMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdSlide"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(Slides);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "Slides"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(SlidesMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, Slides entity)
        {
            
            IMappeableSlidesObject Slides = (IMappeableSlidesObject)entity;
            Slides.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetString(2),
reader.GetString(3),
(reader.IsDBNull(4)) ? "" : reader.GetString(4),
reader.GetInt32(5),
reader.GetBoolean(6));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(Slides entity)
        {

            IMappeableSlidesObject Slides = (IMappeableSlidesObject)entity;
            return Slides.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(Slides entity)
        {

            IMappeableSlidesObject Slides = (IMappeableSlidesObject)entity;
            return Slides.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(Slides entity)
        {

            IMappeableSlidesObject Slides = (IMappeableSlidesObject)entity;
            return Slides.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(Slides entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableSlidesObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(Slides entity)
        {
            
            ((IMappeableSlides)entity).CompleteEntity();
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }


          





        /// <summary>
        /// Get a Slides by execute a SQL Query Text
        /// </summary>
        public Slides GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a SlidesList by execute a SQL Query Text
        /// </summary>
        public SlidesList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public Slides GetOne(System.Int32 IdSlide)
        {
            return base.GetOne(new Slides(IdSlide));
        }


        // GetOne By Objects and Params
            


        


        

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 IdSlide)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Slides_Delete", IdSlide);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdSlide)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Slides_Delete", IdSlide);
        }


        // Delete By Objects and Params
            



        


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace monaguaRules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class SlidesMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public monaguaRules.Mappers.SlidesMapper Instance()
        {
            return monaguaRules.Mappers.SlidesMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a SlidesEntity by calling a Stored Procedure
        /// </summary>
        public Entities.Slides GetOne(System.Int32 IdSlide) {
            return Instance().GetOne( IdSlide);
        }

        // GetBy Objects and Params
            

        

       

        /// <summary>
        /// Delete children for Slides
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, Slides entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        
        /// <summary>
        /// Delete Slides 
        /// </summary>
        public void Delete(System.Int32 IdSlide){
            Instance().Delete(IdSlide);
        }

        /// <summary>
        /// Delete Slides 
        /// </summary>
        public void Delete(Entities.Slides entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save Slides  
        /// </summary>
        public void Save(Entities.Slides entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert Slides 
        /// </summary>
        public void Insert(Entities.Slides entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll Slides 
        /// </summary>
        public Entities.SlidesList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save Slides 
        /// </summary>
        public void Save(System.Int32 IdSlide, System.String Titulo, System.String Descripcion, System.String Foto, System.String Link, System.Int32 Orden, System.Boolean Activo){
            Entities.Slides entity = Instance().GetOne(IdSlide);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "IdSlide", IdSlide));

            entity.Titulo = Titulo;
            entity.Descripcion = Descripcion;
            entity.Foto = Foto;
            entity.Link = Link;
            entity.Orden = Orden;
            entity.Activo = Activo;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert Slides
        /// </summary>
        public void Insert(System.String Titulo, System.String Descripcion, System.String Foto, System.String Link, System.Int32 Orden, System.Boolean Activo){
            Entities.Slides entity = new Entities.Slides();

            entity.Titulo = Titulo;
            entity.Descripcion = Descripcion;
            entity.Foto = Foto;
            entity.Link = Link;
            entity.Orden = Orden;
            entity.Activo = Activo;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace monaguaRules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class SlidesLoader<T> : BaseLoader< T, Slides, ObjectList<T>>, IGenericGateway where T : Slides, new()
    {

        #region "Singleton"

        static SlidesLoader<T> _instance;

        private SlidesLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static SlidesLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new SlidesLoader<T>();
                else {
                    SlidesLoader<T> inst = HttpContext.Current.Items["monaguaRules.SlidesLoaderSingleton"] as SlidesLoader<T>;
                    if (inst == null) {
                        inst = new SlidesLoader<T>();
                        HttpContext.Current.Items.Add("monaguaRules.SlidesLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdSlide"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(Slides);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "Slides"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, Slides entity)
        {
            
            IMappeableSlidesObject Slides = (IMappeableSlidesObject)entity;
            Slides.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetString(2),
reader.GetString(3),
(reader.IsDBNull(4)) ? "" : reader.GetString(4),
reader.GetInt32(5),
reader.GetBoolean(6));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            
            ((IMappeableSlides)entity).CompleteEntity();
        }


        



        /// <summary>
        /// Get a Slides by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a SlidesList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 IdSlide)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "Slides_GetOne", IdSlide);
        }


        // GetOne By Objects and Params
            


        


        

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





