
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 19/5/2022 - 10:51 a. m.
// This is a partial class file. The other one is UsuariosMapper.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using monaguaRules.Objects;
using monaguaRules.Entities;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace monaguaRules.Mappers
{

    /// <summary>
    /// Mapper for Usuarios entity
    /// This class provide persistence methods for this entity
    /// </summary>
    public  partial class UsuariosMapper
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}

        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, UsuariosList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}


namespace monaguaRules.Loaders
{

    /// <summary>
    /// Loader for Usuarios entity
    /// This class provide get methods for this entity
    /// </summary>
    public partial class UsuariosLoader
    {
    }

}



