
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 18/7/2022 - 04:08 p. m.
// This is a partial class file. The other one is EstadosCompraGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using monaguaRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace monaguaRules.Gateways
{

    public partial class EstadosCompraGateway : BaseGateway<EstadosCompraObject, EstadosCompraObjectList>, IGenericGateway
    {

        #region "Singleton"

        static EstadosCompraGateway _instance;

        private EstadosCompraGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static EstadosCompraGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new EstadosCompraGateway();
                else {
                    EstadosCompraGateway inst = HttpContext.Current.Items["monaguaRules.EstadosCompraGatewaySingleton"] as EstadosCompraGateway;
                    if (inst == null) {
                        inst = new EstadosCompraGateway();
                        HttpContext.Current.Items.Add("monaguaRules.EstadosCompraGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "EstadosCompra"; }
        }

        protected override string RuleName
        {
            get {return typeof(EstadosCompraGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, EstadosCompraObject entity)
        {
            
            IMappeableEstadosCompraObject EstadosCompra = (IMappeableEstadosCompraObject)entity;
            EstadosCompra.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetInt32(2));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(EstadosCompraObject entity)
        {

            IMappeableEstadosCompraObject EstadosCompra = (IMappeableEstadosCompraObject)entity;
            return EstadosCompra.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(EstadosCompraObject entity)
        {

            IMappeableEstadosCompraObject EstadosCompra = (IMappeableEstadosCompraObject)entity;
            return EstadosCompra.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(EstadosCompraObject entity)
        {

            IMappeableEstadosCompraObject EstadosCompra = (IMappeableEstadosCompraObject)entity;
            return EstadosCompra.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(EstadosCompraObject row, object[] parameters)
        {
            ((IMappeableEstadosCompraObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a EstadosCompraObject by execute a SQL Query Text
        /// </summary>
        public EstadosCompraObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a EstadosCompraObjectList by execute a SQL Query Text
        /// </summary>
        public EstadosCompraObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a EstadosCompraObject by calling a Stored Procedure
        /// </summary>
        public EstadosCompraObject GetOne(System.Int32 IdEstadoCompra)
        {
            return base.GetOne(new EstadosCompraObject(IdEstadoCompra));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete EstadosCompra
        /// </summary>
        public void Delete(System.Int32 IdEstadoCompra)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "EstadosCompra_Delete", IdEstadoCompra);
        }

        /// <summary>
        /// Delete EstadosCompra
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdEstadoCompra)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "EstadosCompra_Delete", IdEstadoCompra);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








