
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 22/11/2022 - 11:25
// This is a partial class file. The other one is EstadosCompraActividadGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using monaguaRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace monaguaRules.Gateways
{

    public partial class EstadosCompraActividadGateway : BaseGateway<EstadosCompraActividadObject, EstadosCompraActividadObjectList>, IGenericGateway
    {

        #region "Singleton"

        static EstadosCompraActividadGateway _instance;

        private EstadosCompraActividadGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static EstadosCompraActividadGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new EstadosCompraActividadGateway();
                else {
                    EstadosCompraActividadGateway inst = HttpContext.Current.Items["monaguaRules.EstadosCompraActividadGatewaySingleton"] as EstadosCompraActividadGateway;
                    if (inst == null) {
                        inst = new EstadosCompraActividadGateway();
                        HttpContext.Current.Items.Add("monaguaRules.EstadosCompraActividadGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "EstadosCompraActividad"; }
        }

        protected override string RuleName
        {
            get {return typeof(EstadosCompraActividadGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, EstadosCompraActividadObject entity)
        {
            
            IMappeableEstadosCompraActividadObject EstadosCompraActividad = (IMappeableEstadosCompraActividadObject)entity;
            EstadosCompraActividad.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(EstadosCompraActividadObject entity)
        {

            IMappeableEstadosCompraActividadObject EstadosCompraActividad = (IMappeableEstadosCompraActividadObject)entity;
            return EstadosCompraActividad.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(EstadosCompraActividadObject entity)
        {

            IMappeableEstadosCompraActividadObject EstadosCompraActividad = (IMappeableEstadosCompraActividadObject)entity;
            return EstadosCompraActividad.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(EstadosCompraActividadObject entity)
        {

            IMappeableEstadosCompraActividadObject EstadosCompraActividad = (IMappeableEstadosCompraActividadObject)entity;
            return EstadosCompraActividad.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(EstadosCompraActividadObject row, object[] parameters)
        {
            ((IMappeableEstadosCompraActividadObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a EstadosCompraActividadObject by execute a SQL Query Text
        /// </summary>
        public EstadosCompraActividadObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a EstadosCompraActividadObjectList by execute a SQL Query Text
        /// </summary>
        public EstadosCompraActividadObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a EstadosCompraActividadObject by calling a Stored Procedure
        /// </summary>
        public EstadosCompraActividadObject GetOne(System.Int32 IdEstadoActividad)
        {
            return base.GetOne(new EstadosCompraActividadObject(IdEstadoActividad));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete EstadosCompraActividad
        /// </summary>
        public void Delete(System.Int32 IdEstadoActividad)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "EstadosCompraActividad_Delete", IdEstadoActividad);
        }

        /// <summary>
        /// Delete EstadosCompraActividad
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdEstadoActividad)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "EstadosCompraActividad_Delete", IdEstadoActividad);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








