
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 22/6/2022 - 05:03 p. m.
// This is a partial class file. The other one is PaisesGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using monaguaRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace monaguaRules.Gateways
{

    public partial class PaisesGateway : BaseGateway<PaisesObject, PaisesObjectList>, IGenericGateway
    {

        #region "Singleton"

        static PaisesGateway _instance;

        private PaisesGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static PaisesGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new PaisesGateway();
                else {
                    PaisesGateway inst = HttpContext.Current.Items["monaguaRules.PaisesGatewaySingleton"] as PaisesGateway;
                    if (inst == null) {
                        inst = new PaisesGateway();
                        HttpContext.Current.Items.Add("monaguaRules.PaisesGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Paises"; }
        }

        protected override string RuleName
        {
            get {return typeof(PaisesGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, PaisesObject entity)
        {
            
            IMappeablePaisesObject Paises = (IMappeablePaisesObject)entity;
            Paises.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(PaisesObject entity)
        {

            IMappeablePaisesObject Paises = (IMappeablePaisesObject)entity;
            return Paises.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(PaisesObject entity)
        {

            IMappeablePaisesObject Paises = (IMappeablePaisesObject)entity;
            return Paises.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(PaisesObject entity)
        {

            IMappeablePaisesObject Paises = (IMappeablePaisesObject)entity;
            return Paises.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(PaisesObject row, object[] parameters)
        {
            ((IMappeablePaisesObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a PaisesObject by execute a SQL Query Text
        /// </summary>
        public PaisesObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a PaisesObjectList by execute a SQL Query Text
        /// </summary>
        public PaisesObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a PaisesObject by calling a Stored Procedure
        /// </summary>
        public PaisesObject GetOne(System.Int32 IdPais)
        {
            return base.GetOne(new PaisesObject(IdPais));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete Paises
        /// </summary>
        public void Delete(System.Int32 IdPais)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Paises_Delete", IdPais);
        }

        /// <summary>
        /// Delete Paises
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdPais)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Paises_Delete", IdPais);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








